/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-05-25 14:10:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>Form-v8 by Colorlib</title>\r\n");
      out.write("\t<!-- Mobile Specific Metas -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t<!-- Font-->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"sourcesanspro-font.css\">\r\n");
      out.write("\t<!-- Main Style Css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"userstyle.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"form-v8\">\r\n");
      out.write("<marquee direction=\"right\" style=\"background:  #800000;font-size:50px;color:  #00e600;font-style:bold ;font-family:jockman\">\r\n");
      out.write("\t\t\tWelcome To FlyHigh User Login Page\r\n");
      out.write("\t\t</marquee>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page-content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-v8-content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-left\">\r\n");
      out.write("\t\t\t\t<img src=\"flyhigh4.png\" alt=\"form\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-right\">\r\n");
      out.write("\t\t\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-inner\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'sign-up')\" id=\"defaultOpen\">Sign Up</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-inner\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"tablinks\" onclick=\"openCity(event, 'sign-in')\">Sign In</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form class=\"form-detail\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tabcontent\" id=\"sign-up\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"full_name\" id=\"full_name\" class=\"input-text\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">Name</span>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<span class=\"border\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"your_email\" id=\"your_email\" class=\"input-text\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">E-Mail</span>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<span class=\"border\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" class=\"input-text\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">Password</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"border\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row-last\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"register\" class=\"register\" value=\"Register\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form class=\"form-detail\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tabcontent\" id=\"sign-in\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"your_email_1\" id=\"your_email_1\" class=\"input-text\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">E-Mail</span>\r\n");
      out.write("\t\t  \t\t\t\t\t\t<span class=\"border\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-row-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password_1\" id=\"password_1\" class=\"input-text\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label\">Password</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"border\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row-last\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"register\" class=\"register\" value=\"Sign In\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction openCity(evt, cityName) {\r\n");
      out.write("\t\t    var i, tabcontent, tablinks;\r\n");
      out.write("\t\t    tabcontent = document.getElementsByClassName(\"tabcontent\");\r\n");
      out.write("\t\t    for (i = 0; i < tabcontent.length; i++) {\r\n");
      out.write("\t\t        tabcontent[i].style.display = \"none\";\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    tablinks = document.getElementsByClassName(\"tablinks\");\r\n");
      out.write("\t\t    for (i = 0; i < tablinks.length; i++) {\r\n");
      out.write("\t\t        tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    document.getElementById(cityName).style.display = \"block\";\r\n");
      out.write("\t\t    evt.currentTarget.className += \" active\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Get the element with id=\"defaultOpen\" and click on it\r\n");
      out.write("\t\tdocument.getElementById(\"defaultOpen\").click();\r\n");
      out.write("\t</script>\r\n");
      out.write("</body><!-- This templates was made by Colorlib (https://colorlib.com) -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
