/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-04-08 05:06:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.time.*;
import java.sql.*;
import java.io.*;

public final class obooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 

String rname=request.getParameter("bname");
String rfrom=request.getParameter("bfrom");
String rto=request.getParameter("bto");
String rcheckin=request.getParameter("bcheckin");
String rcheckout=request.getParameter("bcheckout");
String rseats = request.getParameter("btotalseats");
int id = (int)(Math.random() * 99999 + 1);
session.setAttribute("bid",id);
session.setAttribute("bname",rname);
session.setAttribute("bfrom",rfrom);
session.setAttribute("bto",rto);
session.setAttribute("bcheckin",rcheckin);
session.setAttribute("bcheckout",rcheckout);
session.setAttribute("bseats",Integer.parseInt(rseats));
try
{
	Connection con=null;
	Class.forName("com.mysql.cj.jdbc.Driver");
	System.out.println("Driver Class Loaded");
	con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flyhigh", "root","root");
	System.out.println("Connection Established");
	 PreparedStatement pstmt = con.prepareStatement("select * from addoffers where ffrom=? and fto=?");
	  pstmt.setString(1,rfrom);
	  pstmt.setString(2,rto);
	  ResultSet rs = pstmt.executeQuery();
	  
	  	  if(rs.next())
	  {
		int cost2=rs.getInt("cost")*Integer.parseInt(rseats);
		int cost3=cost2*rs.getInt("discount")/100;
		int cost1=cost2-cost3;
		System.out.println(cost1);
		session.setAttribute("cost",cost1);
		session.setMaxInactiveInterval(10);
		System.out.println("Total Cost is:"+cost1);
		PreparedStatement pst2=con .prepareStatement("select availseats from addoffers where ffrom='"+rfrom+"' and fto='"+rto+"'");
		ResultSet rs1=pst2.executeQuery();
		rs1.next();
		int c=rs1.getInt("availseats");
		System.out.println("Remaining Seats"+c);
		if(c>=Integer.parseInt(rseats))
		{
		PreparedStatement pstmt1 = con.prepareStatement("insert into booking values(?,?,?,?,?,?,?,?)");
		pstmt1.setInt(1, id);
		 pstmt1.setString(2, rname);
		 pstmt1.setString(3, rfrom);
		 pstmt1.setString(4, rto);
		 pstmt1.setString(5, rcheckin);
		 pstmt1.setString(6, rcheckout);
		 pstmt1.setInt(7, Integer.parseInt(rseats));
		 pstmt1.setInt(8,cost1);
		 pstmt1.executeUpdate();
		int remseats=c-Integer.parseInt(rseats);
		PreparedStatement pst1=con .prepareStatement("update addoffers set availseats="+remseats+" where ffrom='"+rfrom+"' and fto='"+rto+"'");
		pst1.executeUpdate();
		response.sendRedirect("booking1.jsp");
	  }
		else
		{
			out.println("No sufficient seats are available");
		}
	  }
	  else
	  {
		  
      out.write("\r\n");
      out.write("\t\t<center>\t<h3>Book Again</h3></center><br>\r\n");
      out.write("\t <center> <a href=\"flightbooking.html\"> \r\n");
      out.write("      <button class=\"btn btn-secondary\"> \r\n");
      out.write("           Try Again\r\n");
      out.write("        </button> \r\n");
      out.write("    </a> </center>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\t\t\t");
 
	  }
	 
}
catch(Exception e)
{
	out.println(e);
}



    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
