/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-04-08 05:04:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.time.*;
import java.sql.*;
import java.io.*;

public final class viewoffers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<title>Offers</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Karma\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"offersstyle.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body,h1,h2,h3,h4,h5,h6 {font-family: \"Karma\", sans-serif}\r\n");
      out.write(".w3-bar-block .w3-bar-item {padding:20px}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".w3-sidebar a {font-family: \"Roboto\", sans-serif}\r\n");
      out.write("body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: \"Montserrat\", sans-serif;}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"w3-content\" style=\"max-width:1200px\">\r\n");
      out.write("<nav>\r\n");
      out.write("   <div class=\"menu-icon\"><span class=\"fas fa-bars\"></span></div>\r\n");
      out.write("  <div class=\"logo\"><h1>Fly High</h1></div>\r\n");
      out.write("  <div class=\"nav-items\">\r\n");
      out.write("    <li><a href=\"home1.html\">Home</a></li>\r\n");
      out.write("    <li><a href=\"searchflight.html\">Flights</a></li>\r\n");
      out.write("    <li><a href=\"viewoffers.jsp\">Offers</a></li>\r\n");
      out.write("    <li><a href=\"tripideas.html\">Trip Ideas</a></li>\r\n");
      out.write("    <li><a href=\"contactus.html\">Contact Us</a></li>\r\n");
      out.write("    <li><a href=\"aboutus.html\">About Us</a></li>\r\n");
      out.write("  </div>\r\n");
      out.write("  <form action=\"#\">\r\n");
      out.write("    <input type=\"search\" class=\"search-data\" placeholder=\"Search..\" required>\r\n");
      out.write("        <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("  </form>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"jumbtron\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-main w3-content w3-padding\" style=\"max-width:1200px;margin-top:20px\">\r\n");
      out.write("\r\n");
      out.write("  <!-- First Photo Grid-->\r\n");
      out.write("  <div class=\"w3-row-padding w3-padding-16 w3-center\" id=\"food\">\r\n");
      out.write("  \r\n");
      out.write("   ");

Blob image = null;
Connection con = null;
byte[ ] imgData = null ;
Statement stmt = null;
int id,discount;
String ffrom,fto,imagepath;
int c=0;
try 
{
	Class.forName("com.mysql.cj.jdbc.Driver");
	System.out.println("Driver Class Loaded");
	con=DriverManager.getConnection("jdbc:mysql://localhost:3306/flyhigh", "root","root");
	System.out.println("Connection Established");
	ResultSet rs=con.createStatement().executeQuery("select id,ffrom,fto,imgloc,discount from addoffers");
  while(rs.next()) 
  {
    c++;
    id=rs.getInt(1);
    ffrom=rs.getString(2);
    fto=rs.getString(3);
    imagepath=rs.getString(4);
    discount=rs.getInt(5);
    /*response.setContentType("image/gif");
    OutputStream o = response.getOutputStream();
   
    
    o.write(imgData);*/
    System.out.println("Image Location"+imagepath);
    if((c-1)%4==0)
    {
    	
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"w3-quarter\">\r\n");
      out.write("      <img src=");
      out.print(imagepath);
      out.write(" alt=\"Sandwich\" style=\"width:90%\">\r\n");
      out.write("     <h3> <h3>");
      out.print(ffrom);
      out.write("</h3> To <h3>");
      out.print(fto);
      out.write("</h3></h3>\r\n");
      out.write("      <h4><b>");
      out.print(discount);
      out.write("% OFF YOUR PURCHASE</b></h4>\r\n");
      out.write("      <p class=\"expire\">Expires: Jan 03, 2021</p>\r\n");
      out.write("       <a href=\"oflightbooking.html\" class=\"btn btn-primary\">Book now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
 
    }
    else if((c-2)%4==0)
    {
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"w3-quarter\">\r\n");
      out.write("      <img src=");
      out.print(imagepath );
      out.write(" alt=\"Steak\" style=\"width:90%\">\r\n");
      out.write("      <h3> <h3>");
      out.print(ffrom);
      out.write("</h3> To <h3>");
      out.print(fto);
      out.write("</h3></h3>\r\n");
      out.write("      <h4><b>");
      out.print(discount);
      out.write("% OFF YOUR PURCHASE</b></h4>\r\n");
      out.write("      <p class=\"expire\">Expires: Jan 03, 2021</p>\r\n");
      out.write("   <a href=\"oflightbooking.html\" class=\"btn btn-primary\">Book now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
 
    }
    else if((c-3)%4==0)
    { 
     
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"w3-quarter\">\r\n");
      out.write("      <img src=");
      out.print(imagepath );
      out.write(" alt=\"Cherries\" style=\"width:90%\">\r\n");
      out.write("      <h3> <h3>");
      out.print(ffrom);
      out.write("</h3> To <h3>");
      out.print(fto);
      out.write("</h3></h3>\r\n");
      out.write("      <h4><b>");
      out.print(discount);
      out.write("% OFF YOUR PURCHASE</b></h4>\r\n");
      out.write("      <p class=\"expire\">Expires: Jan 03, 2021</p>\r\n");
      out.write("    <a href=\"oflightbooking.html\" class=\"btn btn-primary\">Book now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
 
    }
    else
    {
      
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"w3-quarter\">\r\n");
      out.write("      <img src=");
      out.print(imagepath );
      out.write(" alt=\"Cherries\" style=\"width:90%\">\r\n");
      out.write("      <h3> <h3>");
      out.print(ffrom);
      out.write("</h3> To <h3>");
      out.print(fto);
      out.write("</h3></h3>\r\n");
      out.write("      <h4><b>");
      out.print(discount);
      out.write("% OFF YOUR PURCHASE</b></h4>\r\n");
      out.write("      <p class=\"expire\">Expires: Jan 03, 2021</p>\r\n");
      out.write("    <a href=\"oflightbooking.html\" class=\"btn btn-primary\">Book now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 
    }
  } 
  
  
  
  } 
  catch (Exception e) 
  {
    out.println("Unable To Display image");
    out.println("Image Display Error=" + e.getMessage());
    return;
  } 
  finally 
  {
  try 
  {

  //stmt.close();
  con.close();
  } 
catch (SQLException e) 
{
e.printStackTrace();
}
}

      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
